[package]
name = "resymo-agent"
version = "0.1.0"
edition = "2021"

[dependencies]
async-trait = "0.1"
anyhow = "1"
log = "0.4"
clap = { version = "4", features = ["derive", "env"] }
env_logger = "0.10"
thiserror = "1"
tokio = { version = "1", features = ["full"] }
serde = { version = "1", features = ["derive"] }
serde_json = "1"

sysinfo = { version = "0.29", features = [] }

actix-web = "4"
actix-web-extras = "0.1"
actix-web-httpauth = "0.8"

actix-tls = { version = "3", optional = true, features = ["openssl"] }
openssl = { version = "0.10", optional = true, features = ["v111"] }

[features]
default = [
    "openssl"
]

openssl = [
    "dep:openssl",
    "actix-web/openssl",
    "actix-tls",
    "actix-tls/openssl"
]
